apps/myblog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import HomeView, ArchivesView, AboutView, PhotoView, MusicView, ArticleDetailView, CategoryView, TagListView, TagsView, CategoryListView, search

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', ArchivesView.as_view(), name='archives'),

    url(r'^category_list/$', CategoryListView.as_view(), name='category_list'),    #分类列表页
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category'),

    url(r'^tag_list/$', TagListView.as_view(), name='tag_list'),    #标签列表页
    url(r'^tag/(?P<tag_id>\d+)/$', TagsView.as_view(), name='tag'), #所属标签的文章列表

    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^photo/', PhotoView.as_view(), name='photo'),
    url(r'^music/', MusicView.as_view(), name='music'),
    url(r'^article_detail/(?P<article_id>\d+)/$', ArticleDetailView.as_view(), name='article_detail'),

    url(r'^search/$',search, name="search"),
]

soowhat/urls.py
#-*-coding:utf-8-*-
"""soowhat URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.views.static import serve
# from django.contrib import admin
import xadmin
import myblog
from myblog.views import IndexView
from soowhat.settings import MEDIA_ROOT

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),

    #富文本相关
    url(r'^ueditor/',include('DjangoUeditor.urls' )),

    #myblog下的相关配置
    url(r'^blog/', include('myblog.urls', namespace='blog')),

    #设置上传文件的访问处理
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/about.html
{% extends 'base.html' %}
{% load articleinfo %}
{% get_bloger as admin %}

<!-- {% block menu_box %}
<div id="menu-box">
    <a href="javascript:void(0)" id="menu" data-activates="slide-out" class="button-collapse menu" >
        <span class="nav-btn"></span>
    </a>
</div>
{% endblock menu_box %} -->

{% block article_content %}
<div id="content-outer">
	<div id="content-inner">
		<article id="post">
			<div class="post-page-title" style="background-color:#26A69A;background-image:url({{ MEDIA_URL }}{{ article.image }})">
			  <h2>关于</h2>
			  <p>作者:{{ admin.nickname }} &nbsp;&nbsp; 发布于:
				<time datetime="">
			          {{ article.create_time | date:"Y-m-d H:i:s" }}
				</time>
			  </p>
			</div>
			<div class="post-page-content">
			  {% autoescape off %}
			  {{ article.content }}
			  {% endautoescape off %}
			</div>

			<!--评论块-->
			<!--评论块 PC和WAP自适应版-->
			<div id="SOHUCS" style="padding:10px;" sid={{ article.id }}></div>
			<script type="text/javascript">
			(function(){
			var appid = 'cytaiCTiY';
			var conf = 'prod_961833fadebe00c03cd0def80d4f0af1';
			var width = window.innerWidth || document.documentElement.clientWidth;
			if (width < 960) {
			window.document.write('<script id="changyan_mobile_js" charset="utf-8" type="text/javascript" src="https://changyan.sohu.com/upload/mobile/wap-js/changyan_mobile.js?client_id=' + appid + '&conf=' + conf + '"><\/script>'); } else { var loadJs=function(d,a){var c=document.getElementsByTagName("head")[0]||document.head||document.documentElement;var b=document.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("charset","UTF-8");b.setAttribute("src",d);if(typeof a==="function"){if(window.attachEvent){b.onreadystatechange=function(){var e=b.readyState;if(e==="loaded"||e==="complete"){b.onreadystatechange=null;a()}}}else{b.onload=a}}c.appendChild(b)};loadJs("https://changyan.sohu.com/upload/changyan.js",function(){window.changyan.api.config({appid:appid,conf:conf})}); } })();
			</script>

		  	<script>
		      function disqus() { // DON'T EDIT BELOW THIS LINE
		          var d = document, s = d.createElement('script'),v = d.createElement('script'),disquUrl=document.getElementById("disqus_thread").dataset.diaque;
		          v.id = 'dsq-count-scr'
		          v.src= '//'+disquUrl+'/count.js';
		          s.src = 'https://'+disquUrl+'/embed.js';
		          s.setAttribute('data-timestamp', +new Date());
		          (d.head || d.body).appendChild(v);
		          (d.head || d.body).appendChild(s);
		      }
		  	</script>
		  	<noscript>Please enable JavaScript to view the &lt;a href="https://disqus.com/?ref_noscript"&gt;comments powered by Disqus.&lt;/a&gt;</noscript>
		</article>
	</div>
</div>
{% endblock article_content %}

templates/article_detail.html
{% extends 'base.html' %}

{% load articleinfo %}
{% get_bloger as admin %}

{% block menu_box %}
<div id="menu-box"><a href="javascript:void(0)" id="menu" data-activates="slide-out" class="button-collapse menu"><span class="nav-btn back"></span></a></div>
{% endblock menu_box %}

{% block article_content %}
<div id="content-outer">
  <div id="content-inner">

<article id="post">
  <div class="post-page-title" style="background-color:#26A69A;background-image:url({{ MEDIA_URL }}{{ article_detail.image }})">
  <h2>{{ article_detail.title }}</h2>

  <p>作者:{{ admin.nickname }} &nbsp;&nbsp; 发布于:<time datetime="">
          {{ article_detail.create_time | date:"Y-m-d H:i:s" }}
    </time>
  </p>

  </div>
  <div class="post-page-content">
	{% autoescape off %}
	{{ article_detail.content }}
	{% endautoescape off %}
  </div>

  <!--评论块 PC和WAP自适应版-->
  <div id="SOHUCS" style="padding:10px;" sid={{ article_detail.id }}></div>
  <script type="text/javascript">
  (function(){
  var appid = 'cytaiCTiY';
  var conf = 'prod_961833fadebe00c03cd0def80d4f0af1';
  var width = window.innerWidth || document.documentElement.clientWidth;
  if (width < 960) {
  window.document.write('<script id="changyan_mobile_js" charset="utf-8" type="text/javascript" src="https://changyan.sohu.com/upload/mobile/wap-js/changyan_mobile.js?client_id=' + appid + '&conf=' + conf + '"><\/script>'); } else { var loadJs=function(d,a){var c=document.getElementsByTagName("head")[0]||document.head||document.documentElement;var b=document.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("charset","UTF-8");b.setAttribute("src",d);if(typeof a==="function"){if(window.attachEvent){b.onreadystatechange=function(){var e=b.readyState;if(e==="loaded"||e==="complete"){b.onreadystatechange=null;a()}}}else{b.onload=a}}c.appendChild(b)};loadJs("https://changyan.sohu.com/upload/changyan.js",function(){window.changyan.api.config({appid:appid,conf:conf})}); } })();
  </script>

</article>
<nav class="post-nav">
  <!-- Prev Nav -->
	{% if pre_id|is_greate:"0" %}
	<a href="{% url 'blog:article_detail' pre_id %}" id="post_nav-newer" class="post-nav-content prev-content">
	  新篇
	</a>
	{% endif %}

  <!-- Next Nav -->
  {% if next_id|is_greate:"0" %}
  <a href="{% url 'blog:article_detail' next_id %}" id="post_nav-older" class="post-nav-content next-content">
      旧篇
  </a>
  {% endif %}

</nav>

<!--<div class="post-back"><i class="material-icons">arrow_back</i></div>-->
<script type="text/javascript">
    menu();
</script>
  </div>
</div>
{% endblock article_content %}

templates/article_list.html
{% extends 'base.html' %}

{% block title %}
    {% ifequal request.path|slice:'14' '/blog/archives' %}{{ archive }} - 可可西里没有海{% endifequal %}
    {% ifequal request.path|slice:'14' '/blog/category' %}{{ category_name }} - 可可西里没有海{% endifequal %}
    {% ifequal request.path|slice:'9' '/blog/tag' %}{{ tag_name }} - 可可西里没有海{% endifequal %}
{% endblock title %}

{% block article_content %}

{% ifequal article_list.object_list|length 0 %}
    <div class="no_search">
        查询不到结果!
    </div>
{% endifequal %}

{% for article in article_list.object_list %}
<div class="recent-post-item lazy"style="background-color:#26A69A"   data-original="{{ MEDIA_URL }}{{ article.image }}"  >
  <!-- <a class="recent-post-link" href="{% url 'blog:article_detail' article.id %}"> -->
  <div class="post-hover">
    <!--title-->
    <p class="post-title"><a href="{% url 'blog:article_detail' article.id %}" >{{ article.title }}</a></p>

    <!--date-->

      <p class="post-time">justbreaking &nbsp &nbsp 发布于:<time datetime="">
        {{ article.create_time | date:"Y-m-d H:i:s" }}
      </time>
      </p>

    <!--tags-->

    标签:

        <ul class="tag-list">
            {% for tag in article.tags.all %}
            <li class="tag-list-item"><a class="tag-list-link" href="{% url 'blog:tag' tag.id %}">{{ tag }}</a></li>
            {% endfor %}
        </ul>

    <!--分类-->

    分类:
          <ul class="category-list"><li class="category-list-item">
              <a class="category-list-link" href="{% url 'blog:category' article.category.id %}">{{ article.category.name }}</a></li>
          </ul>


    <!--excerpt-->
    <div class="post-excerpt">
      <p>
        摘要：{{ article.abstract }}
      </p>
    </div>
    <div class="post-more"><a href="{% url 'blog:article_detail' article.id %}" >全文阅读</a></div>
  </div>
  <!-- </a> -->
</div>
{% endfor %}
{% endblock article_content %}

templates/categorylist.html
{% extends 'base.html' %}
{% load articleinfo %}

{% block article_content %}
<div id="content-outer">
	<div id="content-inner">
		<div class="tags">
			<div id="archive">
			  <ul class="tag-list">
				  {% get_categories as category_list %}
				  {% for category in category_list %}
				  <li class="tag-list-item"><a class="tag-list-link" href="{% url 'blog:category' category.id %}">{{ category.name }}</a></li>
				  {% endfor %}
			  </ul>
			</div>
		</div>
	</div>
</div>
{% endblock article_content %}

templates/home.html
{% extends 'base.html' %}

{% block bloger_info %}
<div class="post-header" style="background-image:url({{ MEDIA_URL }}{{ admin.background_image }});background-color:#26A69A ">
    <a  href="http://soowhat.cn"  >
        <div class="post-header-title">
            <p style="">
                你啊你，是自在如风的少年。
                <br>
            </p>
        </div>
    </a>
</div>
<div class="post-author">
    <div class="post-author-img"><img src="{{ MEDIA_URL }}{{ admin.avator }}" ondragstart="return false;"></div>
    <p class="post-author-name">{{ admin.nickname }}</p>
    <div class="post-author-button"  target="_self"><i class="material-icons"  target="_self" style="font-size: 20px">share</i></div>
    <div class="post-author-link"><ul>
            <p>分享到：</p>
            <li><a href="http://v.t.sina.com.cn/share/share.php?url=http://soowhat.cn&title=可可西里没有海's Blog" target="_blank">新浪微博</a></li>
            <li><a href="http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=http://soowhat.cn &desc= 可可西里没有海's Blog" target="_blank">QQ空间</a></li>
            <li><a href="http://connect.qq.com/widget/shareqq/index.html?title=qqhaoyou&url=http://soowhat.cn &desc= 可可西里没有海's Blog" target="_blank">QQ好友</a></li>
        </ul></div>
</div>
{% endblock bloger_info %}

{% block article_content %}
{% for article in article_list.object_list %}
<div class="recent-post-item lazy"style="background-color:#26A69A"   data-original="{{ MEDIA_URL }}{{ article.image }}"  >
  <!-- <a class="recent-post-link" href="{% url 'blog:article_detail' article.id %}"> -->
  <div class="post-hover">
    <!--title-->
    <p class="post-title"><a href="{% url 'blog:article_detail' article.id %}" >{{ article.title }}</a></p>

    <!--date-->

      <p class="post-time">justbreaking &nbsp &nbsp 发布于:<time datetime="">
        {{ article.create_time | date:"Y-m-d H:i:s" }}
      </time>
      </p>

    <!--tags-->

    标签:

        <ul class="tag-list">
            {% for tag in article.tags.all %}
            <li class="tag-list-item"><a class="tag-list-link" href="{% url 'blog:tag' tag.id %}">{{ tag }}</a></li>
            {% endfor %}
        </ul>

    <!--分类-->

    分类:
          <ul class="category-list"><li class="category-list-item">
              <a class="category-list-link" href="{% url 'blog:category' article.category.id %}">{{ article.category.name }}</a></li>
          </ul>


    <!--excerpt-->
    <div class="post-excerpt">
      <p>
        摘要：{{ article.abstract }}
      </p>
    </div>
    <div class="post-more"><a href="{% url 'blog:article_detail' article.id %}" >全文阅读</a></div>
  </div>
  <!-- </a> -->
</div>
{% endfor %}
{% endblock article_content %}

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
{% load articleinfo %}

{% get_bloger as admin %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>可可西里没有海</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width,inital-scale=1,maximum-scale=1.0,user-scalable=no,minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- 百度统计 -->
    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?c0451e16533956173997b85f7a8de666";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
</head>
<body>

    <div class="container">
        <div class="cover-img" style="background: url(http://oct3pmpde.bkt.clouddn.com/wall-39.jpg) no-repeat fixed center center"></div>
        <div class="header">
            <img class="avator" src="{{ MEDIA_URL }}{{ admin.avator }}">
            <nav>
                <ul class="list">
                    <span>soowhat</span>
                    <li><a href="{% url 'blog:home' %}" class="animsition-link website-title" target="" title="博客页"> | 可可西里没有海's blog</a></li>
                    <li><a href="{% url 'blog:home' %}" class="icon-twitter" target=""><i class="fa fa-home" aria-hidden="true" title="博客页"></i></a></li>
                    <li><a href="https://github.com/JustBreaking" class="icon-github" target="_blank"><i class="fa fa-github" aria-hidden="true" title="github"></i></a></li>
                    <li><a href="javascript:void(0)" class="icon-weixin" target="_blank"><i class="fa fa-weixin" aria-hidden="true" title="微信"></i></a></li>
                    <li><a href="http://weibo.com/u/2865881871" class="icon-weibo" target="_blank"><i class="fa fa-weibo" aria-hidden="true" title="微博"></i></a></li>
                    <li class="nolink">
                        <span class="welcome"> Welcome to my website!</span>
                    </li>
                    <img class="codeimg" src="{% static 'images/weixin.jpg' %}">
                </ul>
            </nav>
        </div>
        <div class="section" id="home">
            <p class="glad">剑未佩妥，出门已是江湖
            <p class="glad">酒尚余温，入口不识乾坤</p>
        </div>
    </div>
    <!--移动端-->
    <div id="wrapper">
        <h1>可可西里没有海</h1>
        <h2>永远相信美好的事情即将发生</h2>
        <p><a href="{% url 'blog:home' %}" target="_blank">Blog</a></p>
        <p><a href="https://github.com/JustBreaking" target="_blank">Github</a></p>
        <p><a href="http://music.163.com/#/user/home?id=37479888" target="_blank">网易云音乐</a></p>
        <p><a href="http://weibo.com/justbreaking" target="_blank">微博</a></p>
    </div>
<script>
    var weixin = document.querySelector(".icon-weixin");
    var codeimg = document.querySelector(".codeimg");
    var changeimg = document.querySelector(".avator");
    var cover = document.querySelector(".cover-img");
    var imgbox =   ["http://oct3pmpde.bkt.clouddn.com/wall-388.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-39.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-724.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-303.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-585.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-427.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-32.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-722.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-171.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-1.jpg",
                    "http://oct3pmpde.bkt.clouddn.com/wall-456.jpg"
    ];
    weixin.addEventListener('mouseover',function () {
        codeimg.style.display = "block";
    });
    weixin.addEventListener('mouseout',function () {
        codeimg.style.display = "none";
    });
    changeimg.addEventListener('click',function(){
        var index = Math.floor((Math.random()*imgbox.length));
        var temp = 'url(' + imgbox[index]+ ') no-repeat fixed center center';
        cover.style.background = temp;
    });

</script>
</body>
</html>

templates/taglist.html
{% extends 'base.html' %}
{% load articleinfo %}

{% block article_content %}
<div id="content-outer">
	<div id="content-inner">
		<div class="tags">
			<div id="archive">
			  <ul class="tag-list">
				  {% get_tags as tag_list %}
				  {% for tag in tag_list %}
				  <li class="tag-list-item"><a class="tag-list-link" href="{% url 'blog:tag' tag.id %}">{{ tag.name }}</a></li>
				  {% endfor %}
			  </ul>
			</div>
		</div>
	</div>
</div>
{% endblock article_content %}